import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useState, useEffect } from "react";

import { ethers } from "ethers";
import { useEthers, useContractFunction } from "@usedapp/core";

import { abi } from "../constants/abi";
import { contractAddress } from "../constants/contract-address";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { activateBrowserWallet, account } = useEthers();
  const [hasMetamask, setHasMetamask] = useState(false);

  useEffect(() => {
    if (typeof window.ethereum !== "undefined") {
      setHasMetamask(true);
    }
  });

  async function connect() {
    await activateBrowserWallet();
  }

  const contract = new ethers.Contract(contractAddress, abi);
  const { send, state } = useContractFunction(contract, "store", {
    transactionName: "store",
  });

  useEffect(() => {
    console.log(`State: ${state.status}`);
  }, [state]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          {" "}
          {hasMetamask ? (
            account ? (
              "Connected! "
            ) : (
              <button onClick={() => connect()}>Connect</button>
            )
          ) : (
            "Please install metamask"
          )}
          {account ? <button onClick={() => send(42)}>Execute</button> : ""}
        </div>
      </main>
    </>
  );
}
